[build]
  # Triggering new deployment
  command = "npm run build"
  publish = "out"
  base = "space-portal"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = ""
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = ""
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ""
  NEXT_PUBLIC_FIREBASE_APP_ID = ""
  RESEND_API_KEY = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
