[build]
  # Triggering new deployment
  command = "nvm install 18.19.1 && nvm use 18.19.1 && npm run build"
  publish = "out"
  base = "space-portal"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "9.9.2"
  NEXT_PUBLIC_FIREBASE_API_KEY = ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = ""
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = ""
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ""
  NEXT_PUBLIC_FIREBASE_APP_ID = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
