[build]
  # Triggering new deployment
  command = "npm run build"
  base = "space-portal"
  functions = "functions"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXqXq"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "spli-ai.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "spli-ai"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "spli-ai.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1234567890"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:1234567890:web:abcdef1234567890"
  RESEND_API_KEY = ""

  NEXTAUTH_URL = "https://spli.ai"
  NEXTAUTH_SECRET = "jQfUzTmZKZgrIgYhzp/KfckOIln6XICaBeZZ10/vWGQ="
  AZURE_AD_CLIENT_ID = "13cd9ed7-f7da-4e62-918a-bc90795cb6b4"
  AZURE_AD_CLIENT_SECRET = "w.48Q~zpZXt7zCiDeuq2R6MFHpzKDjgLpjLpi4PaKk"

[[plugins]]
  package = "@netlify/plugin-nextjs"
