[build]
  # Triggering new deployment
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
